WiX: Add missing `\usr\lib\swift\clang`
apple/swift-installer-scripts pull request #144
Opened 2022-09-20 15:25 UTC by stevapple

This is required for Swift compiler to consume Clang resources correctly on Windows.

Fixes apple/swift#60534

2022-09-20 15:31 UTC, stevapple commented
@compnerd You said that CMake could be used for `Atomics`, but that's not true for released toolchains — it only works with a development build, where `\usr\lib\swift\clang` was just there.

2022-09-20 15:33 UTC, stevapple commented
These two harvested directories are mostly the same (except that `ClangResources` are prefixed with Clang version), but I'm not so familiar with WiX to reuse them. This just works (with least modification).

2023-02-08 01:40 UTC, shahmishal commented
cc: @compnerd

2023-03-06 10:14 UTC, stevapple commented
Ping

2023-03-13 14:56 UTC, compnerd requested changes
This is not the place to do this.  There is no need for the duplicated content - it already is in \usr\lib\clang.  The Swift driver should be taught to adjust the `-resource-dir`.

2023-03-13 15:18 UTC, stevapple commented
> The Swift driver should be taught to adjust the `-resource-dir`.

Where do you want to adjust the resource dir to? The resource directory for Swift is `/usr/lib/swift` for all platforms, and for Clang that’s `/usr/lib/clang`. We need to expose Clang’s extra resource headers to Swift, that’s why we have a symlink on other platforms.

2023-03-13 15:30 UTC, compnerd commented
> > The Swift driver should be taught to adjust the `-resource-dir`.
> 
> Where do you want to adjust the resource dir to? The resource directory for Swift is `/usr/lib/swift` for all platforms, and for Clang that’s `/usr/lib/clang`. We need to expose Clang’s extra resource headers to Swift, that’s why we have a symlink on other platforms.

`/usr/lib/clang`, as the content is just duplicating it.  The other platforms have symlinks and de-duplicates that data, Windows does not (and we cannot create them without Administrator rights and a custom action and C++ code).

2023-03-13 15:34 UTC, stevapple commented
> `/usr/lib/clang`, as the content is just duplicating it.

Plz don’t do that😅 We have plenty of other stuffs in `/usr/lib/swift` as Swift resources and this is a conventional path. If you don’t like the idea of symlink (I don’t like it, too), then we’ll end up duplicating this.

2023-03-13 15:36 UTC, compnerd commented
I don't think that duplicating it is reasonable, the toolchain is growing far too fast.  Having the installer hit gigabytes is not a good idea (we are already pushing the boundary on the sizes).  I'm working towards restructuring the MSIs to reduce some of the high pressure on the size.

2023-03-13 17:28 UTC, stevapple commented
We first need to make things work™ in a correct way — even if that’s not optimal, since we can always refine later.

If size limit cannot be worked around, then we need to bring back custom actions for copying/removing Clang resources for Swift automatically.

2023-03-13 17:30 UTC, compnerd commented
I don't think that is reasonable.  The builds are taking longer and longer, we have increased build times ~100% already, we need to do this the proper way the first time around.

2023-03-13 17:35 UTC, stevapple commented
The build time increase is: 1. not Windows-specific, 2. almost not impacted by packaging. This shouldn’t affect decisions on packaging — I believe you should better complain to the Swift compiler & LLVM team.

2023-03-13 17:35 UTC, compnerd commented
The packaging is part of the build times.

2023-03-13 17:40 UTC, stevapple commented
How was that related? When we had custom actions before, it only takes less than 30 seconds to build, compared to over 5 hours of toolchain (LLVM & Swift) build time. How would you think adding a one-minute step hugely affects the total build time?

2023-03-13 17:41 UTC, compnerd commented
The compression overheads add a significant amount of time.  I'd like to reduce the overzealous compression that we are reliant on currently.  Additionally, since the motivation here is the swift-atomics, I'd suggest we understand why building with CMake works and with SPM does not.  The same layout is used by both.

2023-03-13 17:45 UTC, stevapple commented
You’re making false assumptions again and again around this problem. Building Atomics with CMake never works for a released toolchain because it’s missing Clang resources. If you use a freshly-built toolchain instead, CMake and SwiftPM both work out of the box.

2023-03-13 17:47 UTC, compnerd commented
> You’re making false assumptions again and again around this problem. Building Atomics with CMake never works for a released toolchain because it’s missing Clang resources. If you use a freshly-built toolchain instead, CMake and SwiftPM both work out of the box.

I've built it locally, it wasn't a false assumption.  Isolating and resolving those differences is important to make sure that things remain working overtime.  A fair amount of work is going into reducing those differences.

2023-03-13 17:59 UTC, compnerd commented
Yes, the custom action should resolve that.  Would you be up for writing a new custom action for that?  I think that getting a new toolchain snapshot is a bit more pressing atm, so I won't be able to do that for a while.  Guess that we won't be able to support per-user installation after all.

2023-03-13 19:34 UTC, stevapple commented
@compnerd I dug into the Atomic case again and still believe CMake is identical to SwiftPM on handling Clang headers.

The good news is: Visual Studio 17.5 introduces support for C11 `stdatomic.h`, so now Atomics can be built on even older toolchains.

With older MSVC both CMake and SwiftPM should fail to build it because MSVC version of `stdatomic.h` is either non-existent or unusable.

2023-05-25 04:15 UTC, stevapple commented
Superceded by https://github.com/apple/swift-installer-scripts/pull/198

2023-05-25 04:15 UTC, closed without merging